spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my-local
    username: postgres
    password: manager123
    driver-class-name:  org.postgresql.Driver
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update