name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build Application
        run: mvn clean package

      - name: Deploy Application
        run: |
          cd target
          java -jar spring-filter.jar
